-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE user_editcredit (
  ue_id INT NOT NULL,
  ue_credit INT NOT NULL,
  PRIMARY KEY(ue_id)
);

CREATE INDEX ue_credit ON user_editcredit (ue_credit);
