-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/EditCredit/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/edit_credit (
  ec_id INT UNSIGNED NOT NULL,
  ec_credit INT UNSIGNED NOT NULL,
  INDEX ec_credit (ec_credit),
  PRIMARY KEY(ec_id)
) /*$wgDBTableOptions*/;
