-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/EditCredit/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/user_editcredit (
  uc_id INT UNSIGNED NOT NULL,
  uc_credit INT UNSIGNED NOT NULL,
  INDEX uc_credit (uc_credit),
  PRIMARY KEY(uc_id)
) /*$wgDBTableOptions*/;
